plugins {
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlin.spring)
    alias(libs.plugins.kotlin.kapt)
}

group = "com.lamnguyen"
version = "0.0.1-SNAPSHOT"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(libs.spring.boot.oauth2.resource.server)
    implementation(libs.spring.boot.webflux)
    implementation(libs.spring.boot.validation)
    implementation(libs.spring.boot.actuator)
    implementation(libs.spring.boot.rsocket)
    implementation(libs.jackson.kotlin)
    implementation(libs.kotlin.reflect)
    implementation(libs.kotlin.stdlib)
    implementation(libs.kotlin.coroutines.reactor)
    implementation(libs.reactor.kotlin)
    implementation(libs.kafka.streams)
    implementation(libs.spring.kafka)
    implementation(libs.spring.boot.data.mongodb)
    implementation(libs.spring.security.rsocket)
    implementation(libs.libphonenumber)
    implementation(libs.springdoc.webflux)
    implementation(libs.commons.lang3)
    implementation(libs.mapstruct)
    kapt(libs.mapstruct.processor)
    implementation(libs.redisson)
    implementation(libs.redisson.spring.data)
    implementation(libs.kryo)
    implementation(libs.uuid.generator)
    implementation(libs.jackson.jsr310)
}

kotlin {
    compilerOptions {
        freeCompilerArgs.addAll("-Xjsr305=strict")
    }
}