spring:
  application:
    name: chatwsrouter

  profiles:
    active: local

  jackson:
    property-naming-strategy: SNAKE_CASE

  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:9092,localhost:9093,localhost:9094}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: ChatMessage
            type:
              mapping: ChatMessage:com.ndlamdev.chatwsrouter.domain.message.ChatMessage
server:
  port: ${SERVER_PORT:8006}
