spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-whitelist
              uri: http://localhost:8001
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

server:
  port: ${GATEWAY_PORT:8000}
