spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-whitelist
              uri: http://localhost:8001
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1
            - id: user-blacklist
              uri: http://localhost:8003
              predicates:
                - Path=/user/**
              filters:
                - StripPrefix=1
                - name: Authentication
            - id: chat-blacklist
              uri: http://localhost:8004
              predicates:
                - Path=/chat/**
              filters:
                - StripPrefix=1
                - name: Authentication
            - id: chat-ws-whitelist
              uri: ws://localhost:8005
              predicates:
                - Path=/chat-ws/**
              filters:
                - StripPrefix=1
          globalcors:
            cors-configurations:
              '[/**]': # Applies to all paths
                allowed-origins:
                  -  "http://localhost:3000" # Replace with your client's origin(s)
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS # Essential for pre-flight requests
                allowedHeaders:
                  - "*" # Allow all headers, or specify specific ones like "Authorization"
                allowCredentials: true # Set to true if you are using credentials (e.g., cookies, authorization headers)
                maxAge: 3600 # Cache pre-flight response for 1 hour
            add-to-simple-url-handler-mapping: true



  profiles:
    active: local

server:
  port: ${GATEWAY_PORT:8000}
