spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-whitelist
              uri: http://localhost:8001
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1
            - id: user-blacklist
              uri: http://localhost:8003
              predicates:
                - Path=/user/**
              filters:
                - StripPrefix=1
                - name: Authentication
            - id: chat-ws-whitelist
              uri: ws://localhost:8005
              predicates:
                - Path=/chat-ws/**
              filters:
                - StripPrefix=1

  profiles:
    active: local

server:
  port: ${GATEWAY_PORT:8000}
