plugins {
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlin.spring)
}

group = "com.lamnguyen"
version = "0.0.1-SNAPSHOT"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(libs.spring.boot.actuator)
    implementation(libs.spring.boot.data.redis.reactive)
    implementation(libs.spring.boot.websocket)
    implementation(libs.spring.boot.rsocket)
    implementation(libs.spring.boot.oauth2.resource.server)
    implementation(libs.spring.boot.validation)
    implementation(libs.jackson.kotlin)
    implementation(libs.kotlin.reflect)
    implementation(libs.kotlin.coroutines.reactor)
    implementation(libs.reactor.kotlin)
    implementation(libs.redisson)
    implementation(libs.redisson.spring.data)
    implementation(libs.spring.kafka)
}

kotlin {
    compilerOptions {
        freeCompilerArgs.addAll("-Xjsr305=strict")
    }
}