services:
  jenkin:
    image: jenkins/jenkins:lts
    container_name: jenkins_container
    ports:
      - "8080:8080"
      - "50000:5000"
    volumes:
      - ./data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock