syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.lamnguyen.chat.protos";
option java_outer_classname = "UserProto";

import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";

service UserService {
  rpc CheckFriendShip(FriendShipCheckRequest) returns(FriendShipCheckResponse);
}

message FriendShipCheckRequest{
  repeated string friend_phone_numbers = 2;
}

message FriendShipCheckResponse {
  repeated UserInfo friends = 2;
}

message UserInfo {
  google.protobuf.StringValue display_name = 1;
  google.protobuf.BoolValue is_friend = 2;
  google.protobuf.BoolValue add_friend_requested = 3 ;
  string phone_number = 4;
  google.protobuf.StringValue fullName = 5;
  google.protobuf.Timestamp birth_date = 6;
  google.protobuf.StringValue avatar = 7;
  google.protobuf.StringValue email = 8;
  google.protobuf.Timestamp created_at = 9;
  google.protobuf.Timestamp updated_at = 10;
  google.protobuf.StringValue created_by = 11;
  google.protobuf.StringValue updated_by = 12;
  bool locked = 13;
  bool deleted = 14;
}

message RoomChatIdRequest {
  int64 room_chat_id = 1;
}

message MemberOfRoomChatResponse {
  repeated UserInfo user = 1;
}