spring:
  application:
    name: chat-ws

  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:9092,localhost:9093,localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: ChatMessage:com.lamnguyen.chatws.domain.messages.ChatMessage

  profiles:
    active: ${PROFILE:local}


server:
  port: ${CHAT_WS_PORT:8005}

logging:
  level:
    org.springframework.messaging: trace