plugins {
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlin.spring)
    alias(libs.plugins.kotlin.kapt)
}

group = "com.lamnguyen"
version = "0.0.1-SNAPSHOT"

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(libs.spring.boot.actuator)
    implementation(libs.spring.boot.data.r2dbc)
    implementation(libs.spring.boot.webflux)
    implementation(libs.spring.boot.validation)
    implementation(libs.spring.boot.oauth2.resource.server)
    implementation(libs.spring.boot.data.redis.reactive)
    implementation(libs.spring.boot.rsocket)
    implementation(libs.jackson.kotlin)
    implementation(libs.kotlin.reflect)
    implementation(libs.kotlin.coroutines.reactor)
    implementation(libs.reactor.kotlin)
    implementation(libs.spring.kafka)
    implementation(libs.flyway.core)
    implementation(libs.flyway.mysql)
    runtimeOnly(libs.r2dbc.mysql)
    runtimeOnly(libs.mysql.driver)
    compileOnly(libs.lombok)
    annotationProcessor(libs.lombok)
    implementation(libs.libphonenumber)
    implementation(libs.springdoc.webflux)
    implementation(libs.commons.lang3)
    implementation(libs.mapstruct)
    kapt(libs.mapstruct.processor)
    implementation(libs.jackson.jsr310)
    implementation(libs.redisson)
    implementation(libs.redisson.spring.data)
}

kotlin {
    compilerOptions {
        freeCompilerArgs.add("-Xjsr305=strict")
    }
}